[package]
name = "rusttracer"
version = "0.1.0"
authors = ["Derek Erdmann <derek@derekerdmann.com>"]

[[bin]]
name = "rusttracer"

[dependencies]
piston_window = "0.66.0"
image = "0.13.0"
cgmath = "0.15.0"
approx = "0.1.1"
chan = "0.1.19"
time = "0.1.38"